name: example
description: Demonstrates how to use the fl_mlkit_text_recognize plugin.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:


  fl_mlkit_text_recognize:
    path: ../
  flutter:
    sdk: flutter
  flutter_curiosity: ^4.0.1
  flutter_waya: ^2.2.0
  permission_handler: ^10.0.0
  camera: ^0.9.5+1
  path_provider: ^2.0.11
  path: ^1.8.2
  image_gallery_saver: ^1.6.0
  webview_flutter: ^3.0.4


dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: SingleDay
      fonts:
        - asset: assets/fonts/SingleDay-Regular.ttf
    - family: SingleDay
      fonts:
        - asset: assets/fonts/D2Coding-ligature.ttf



